name: Suggest Mod
description: Suggest mods to be added to Every Compat
title: "[📦]: "
labels: "module"
body:
  - type: markdown
    attributes:
      value: |
        MOD SUGGESTION

  - type: input
    id: curseforge
    attributes:
      label: Curseforge
      description: "The link for mod's Curseforge"
      placeholder: ex. https://www.curseforge.com/minecraft/mc-mods/giacomos-bookshelf
    validations:
      required: true

  - type: checkboxes
    id: version-availability
    attributes:
      label: Version Availability
      description: "Multiple Selection: which version is the mod available in?"
      options:
        - label: 1.18.2
        - label: 1.19.2
        - label: 1.20.1
    validations:
      required: true

  - type: checkboxes
    id: loader
    attributes:
      label: loader
      description: "Multiple Selection: which loader is the mod available in?"
      options:
        - label: Forge
        - label: Fabric
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "Types"
      description: "Type of blocks are in the mod?"
      value: "## Block:\n- ex: chair\n\n## Item:\n- <item-name with wood_type>"
    validations:
        required: true

  - type: textarea
    attributes:
      label: Optional Details
      description: |
        A note that we should keep in mind regarding the mod
      placeholder: "ex: Giacomo's Bookshelf can store books and, configurably, other items. Updates front texture\nthrough 4 stages (empty, slightly full, more full, completely full) depending on if 0, 1, 2, or 3+ books are stored"
    validations:
      required: false
