name: Labeling new issue
on:
  issues:
    types: ['opened', 'edited']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/workflows/issue_label.json5
          sparse-checkout-cone-mode: false
      - uses: Renato66/auto-label@v3.1.0
        with:
          repo-token: ${{ secrets.AUTO_LABEL }}
          ignore-comments: true
          configuration-file: .github/workflows/issue_label.json5
          labels-not-allowed: true
